Projeto=Fintech Mobile Automation
SDET_Responsavel=Eduardo Lima de Sousa
Especialidade=QA Automation & SDET
LinkedIn=https://www.linkedin.com/in/eduardolsousa
GitHub=https://github.com/eduardosousa1992
Device=Celular_Automacao (Emulator-5554)
SO=Windows 11
Java_Version=17
Appium_Version=2.x
